### ISSUE TITLE
Z flags not set in OTIR and OTDR instructions

### ISSUE THREAD

**Issue by ITotalJustice** [superzazu/z80#4]
not 100% sure if it's a bug, but according to <https://clrhome.org/table/>, Z should be set to 1 for those instructions. for `outi` and `outd` they set the z flag based on the value of B, so you'd just just need to add it after calling <https://github.com/superzazu/z80/blob/12f9333141509f7e55a3e7b8782d29cf7537d4c7/z80.c#L1649>

**Comment by superzazu** [comment]
If I recall correctly, OTIR & OTDR are loops over OUTI & OUTD until B = 0. In the function `outi()` (which is called in the implementation of both instructions) we have `z->zf = z->b == 0;` which correctly sets Z to 1 when B = 0 (in the last iteration of the loop), so it seems to me that we don't need to add `z->zf = 1` manually?

Please correct me if I made a mistake (it's been a while since I've worked on Z80), and thank you for opening the issue.

**Comment by ITotalJustice** [comment]
sorry for the almost year late reply!

> If I recall correctly, OTIR & OTDR are loops over OUTI & OUTD until B = 0. In the function `outi()` (which is called in the implementation of both instructions) we have `z->zf = z->b == 0;` which correctly sets Z to 1 when B = 0 (in the last iteration of the loop), so it seems to me that we don't need to add `z->zf = 1` manually?

yes that does seem to be the case, thank you for explaining that
